### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by orchid00** [kamermanpr/satRday2018#1]
Hi, I'm trying to understand why does the Nelson product changes the y limit axis to 60. As shown on page 29 of the slides.
I've reproduced the example and I think it is something with the geom_smooth. What could be the problem?

**Comment by orchid00** [comment]
Well, I figure out that the problem is between geom_smooth and Age_group on plot3. I don't know why Age_group makes Nelson Bitrerness have a hump that affects the y axis.
In any case, to resolve the issue of the axis, I've changed the method of geom_smooth to glm
geom_smooth(method = "glm") 

I understand this might be some problem with the geom and there's no reason why you should bother, so feel free to close this issue. 
Although, if you know why it affects the axis I will be really interested to know. thanks!

**Comment by kamermanpr** [comment]
Thanks for your comment Paula. You're 100% correct, the bump is caused by the default level of smoothing by the loess method (span = 0.75 by default -- I think), which seems to battle with the lack of data at bitterness ratings of 3 in the <25 years age group. As you pointed out, you can fix the issue by specifying an alternative the smoothing method (e.g., 'lm', 'glm', 'gam') in `ggplot2::geom_smooth`, or you can play with the degree of smoothing used in the the 'loess' method by playing with the span parameter (see below):

``` r
# Load packages
library(tidyverse)
library(carrots)

# Process and plot
carrots %>% 
    # Select select product and age group of interest
    filter(Product == 'Nelson') %>% 
    filter(Age_group == '< 25 years') %>% 
    # Select columns
    select(Bitterness, Preference) %>% 
    # Plot
    ggplot(data = .) +
    aes(x = Bitterness,
        y = Preference) +
    labs(title = 'Nelson carrots: preference vs bitterness in people < 25 years') +
    geom_point() +
    # Default smoothing span (see ?stats::loess)
    geom_smooth(method = 'loess',
                span = 0.75,
                colour = 'blue') +
    # Increase smoothing span
    geom_smooth(method = 'loess',
                span = 0.85,
                colour = 'red')
```

![](https://i.imgur.com/2V7aW6r.png)

Created on 2018-03-27 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).
